List<String> ocklock = [
  '7 PM',
  '8 PM',
  '9 PM',
  '10 PM',
  '11 PM',
  '12 PM',
  '7 PM',
  '8 PM',
  '9 PM',
  '10 PM',
  '11 PM',
  '12 PM',
  '7 PM',
  '8 PM',
  '9 PM',
  '10 PM',
];

List<String> imageUrl = [
  'assets/images/1.png',
  'assets/images/1.png',
  'assets/images/2.png',
  'assets/images/4.png',
  'assets/images/4.png',
  'assets/images/2.png',
  'assets/images/1.png',
  'assets/images/1.png',
  'assets/images/2.png',
  'assets/images/4.png',
  'assets/images/4.png',
  'assets/images/2.png',
  'assets/images/1.png',
  'assets/images/1.png',
  'assets/images/2.png',
  'assets/images/4.png',
];
